apiVersion: v1
kind: Service
metadata:
  name: nginx-example
  namespace: default
spec:
  allocateLoadBalancerNodePorts: true
  # clusterIP: 172.20.129.194
  # clusterIPs:
  # - 172.20.129.194
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30766
    port: 80
  selector:
    App: ScalableNginxExample
  type: LoadBalancer
